### ISSUE TITLE
Inconsistent results between Docker image and local Terrascan version

### ISSUE THREAD

**Issue by HorizonNet** [tenable/terrascan#1174]
* terrascan version: 1.12.0
* Operating System: MacOS

### Description

When discovering #1172 it looked like changes from newer versions are also pushed to older Docker images, in that case the changes from #1153 were also active in the tag v1.12.0 of the Docker image. Using the same version locally (installed via brew) does not lead to the same violations being reported.

### What I Did

Running the Docker image via

```sh
docker run --rm -it -v "$(pwd):/iac" -w /iac accurics/terrascan:1.12.0 scan --policy-type aws --output yaml
```

resulted in the following report

```
violations:
        - rule_name: s3Versioning
          description: Enabling S3 versioning will enable easy recovery from both unintended user actions, like deletes and overwrites
          rule_id: AC_AWS_0214
          severity: HIGH
          category: Resilience
          resource_name: example
          resource_type: aws_s3_bucket
          module_name: root
          file: main.tf
          plan_root: ./
          line: 29
        - rule_name: s3Versioning
          description: Enabling S3 versioning will enable easy recovery from both unintended user actions, like deletes and overwrites
          rule_id: AC_AWS_0214
          severity: HIGH
          category: Resilience
          resource_name: example2
          resource_type: aws_s3_bucket
          module_name: root
          file: main.tf
          plan_root: ./
          line: 115
    skipped_violations: []
    scan_summary:
        file/folder: /iac
        iac_type: all
        scanned_at: 2022-02-27 14:53:04.6080697 +0000 UTC
        policies_validated: 14
        violated_policies: 2
        low: 0
        medium: 0
        high: 2
```

Using the same version and the same Terraform files locally

```sh
terrascan scan --policy-type aws --output yaml
```

the report looks like the following

```
violations: []
    skipped_violations: []
    scan_summary:
        file/folder: /test
        iac_type: all
        scanned_at: 2022-02-27 14:53:35.604217 +0000 UTC
        policies_validated: 14
        violated_policies: 0
        low: 0
        medium: 0
        high: 0
```
