### ISSUE TITLE
Kustomize - must specify --enable-helm

### ISSUE THREAD

**Issue by CodeReaper** [tenable/terrascan#1649]
* terrascan version: 1.18.5
* Operating System: macOS 14.1.1 (23B81)

### Description

I attempted to scan some kustomize and helm configuration in our IaC repo using the GitHub Action. It reported an error that kustomize requires an additional argument to allow the usage of helm. I reproduced the same issue locally and have not found a way to specify that kustomize should allow helm.

Error:
```
2023-11-30T19:35:27.621+0100	error	cli/run.go:141	scan run failed{error 26 0  1 error occurred:
	* error occurred while loading kustomize directory '<removed path>'. err: error from kustomization. error : trouble configuring builtin HelmChartInflationGenerator with config: `
name: argo-cd
namespace: argocd
releaseName: argocd
repo: https://argoproj.github.io/argo-helm
version: 5.46.8
`: must specify --enable-helm

}
```

### What I Did

I scanned the following:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

helmCharts:
  - name: argo-cd
    releaseName: argocd
    namespace: argocd
    repo: https://argoproj.github.io/argo-helm
    version: 5.46.8

```

... using the following command:

```
terrascan scan -d some/folder -i kustomize --iac-version v4
```
