### ISSUE TITLE
cli/init.go:42	failed to initialize terrascan. error : failed to download policies. error: 'repository already exists'

### ISSUE THREAD

**Issue by zoezhangmattr** [tenable/terrascan#1728]
we are using pre-commit, with terrascan
pre-commit version 4.1.0
terrascan version 1.19.9
terraform version 1.11.1

pre-commit config
```yaml
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.4
    hooks:
    - id: terrascan
      args:
          - >
            --args=--severity High --non-recursive
```
when running precommit in github workflow.
we dont specify any terrascan extra configs. or policy configs. 
the error occurs
cli/init.go:42	failed to initialize terrascan. error : failed to download policies. error: 'repository already exists'

what i tried, 
remove ~/.terrascan folder (even though nothing is there) just make sure there is no such folder in the github runner.
nothing works

could you help please
